GPU Exponential Integrator: src/magma_test/zfill.h File Reference
zfill.h File Reference
#include "magma.h"
Functions
void zfill_matrix (magma_int_t m, magma_int_t n, magmaDoubleComplex *A, magma_int_t lda)
void zfill_rhs (magma_int_t m, magma_int_t nrhs, magmaDoubleComplex *X, magma_int_t ldx)
void zfill_matrix_gpu (magma_int_t m, magma_int_t n, magmaDoubleComplex *dA, magma_int_t ldda)
void zfill_rhs_gpu (magma_int_t m, magma_int_t nrhs, magmaDoubleComplex *dX, magma_int_t lddx)
Function Documentation
void zfill_matrix (magma_int_t m, magma_int_t n, magmaDoubleComplex * A, magma_int_t lda)
Definition at line 28 of file zfill.c.
Referenced by cpu_interface(), zfill_matrix_gpu(), and zfill_rhs().
void zfill_matrix_gpu (magma_int_t m, magma_int_t n, magmaDoubleComplex * dA, magma_int_t ldda)
Definition at line 56 of file zfill.c.
References A, and zfill_matrix().
Referenced by gpu_interface(), and zfill_rhs_gpu().
void zfill_rhs (magma_int_t m, magma_int_t nrhs, magmaDoubleComplex * X, magma_int_t ldx)
Definition at line 45 of file zfill.c.
References zfill_matrix().
Referenced by cpu_interface().
void zfill_rhs_gpu (magma_int_t m, magma_int_t nrhs, magmaDoubleComplex * dX, magma_int_t lddx)
Definition at line 74 of file zfill.c.
References zfill_matrix_gpu().
Referenced by gpu_interface().